export const ITEMS_PER_PAGE_OPTIONS = [5, 10, 20];
export const DEFAULT_ITEMS_PER_PAGE = 5;
export const MOBILE_TABLE_HEIGHT_DIVIDER = 3;
export const DESKTOP_TABLE_HEIGHT_DIVIDER = 2.5;
export const PAGINATION_OPACITY_THRESHOLD = 4;
export const PAGINATION_MOBILE_WIDTH = 320;
export const PAGINATION_DESKTOP_WIDTH = 500;
